version: '3.8'

services:
  api:
    build:
      args:
        - NODE_ENV=development
      # environment:
      #   - NODE_ENV=development
    command: npm run dev
  client:
    build:
      args:
        - NODE_ENV=development
    command: npm start
      #     networks:
      #       - shared-network
  nginx:
    ports:
      - 3000:80

volumes:
  mongo-db:
    # networks:
    #   shared-network:
