version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: shopfinder_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  api:
    build:
      args:
        - NODE_ENV=production
      environment:
        - NODE_ENV=production
    command: [ "/bin/sh", "-c", "npm run build;npm  start" ]
  client:
    build:
      args:
        - NODE_ENV=development
    command: [ "npm run build;serve build" ]
volumes:
  mongo-db:
    # networks:
    #   shared-network:
