version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: shopfinder_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  api:
    container_name: shopfinder_api
    # restart: unless-stopped
    image: shopfinder_api:1.0.0
    build:
      context: api
      # target: prod
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=LAJGLKJDFNLKJDNFHLKJNL43JK562L4KJNLJKN
    # ports:
    #   - 5000:5000
    depends_on:
      - mongodb
  client:
    container_name: shopfinder_client
    # restart: unless-stopped
    image: shopfinder_client:1.0.0
    build:
      context: client
      # target: prod
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    depends_on:
      - api
  nginx:
    image: nginx:stable-alpine
    container_name: shopfinder_nginx
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    # volumes:
    #   - /default.conf:/etc/nginx/conf.d/default.conf:ro
    #     networks:
    #       - shared-network
volumes:
  mongo-db:
    # networks:
    #   shared-network:
